import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {ScrollingModule} from '@angular/cdk/scrolling';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatCardModule,
  MatToolbarModule,
  MatIconModule,
  MatDialogModule,
  MatTooltipModule,
  MatFormFieldModule,
  MatStepperModule,
  MatInputModule,
  MatSelectModule,
  MatMenuModule,
  MatSidenavModule,
  MatDividerModule,
  MatSnackBarModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatListModule,
  MatGridListModule,
  MatBadgeModule,
  MatTreeModule,
  MatTableModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatSortModule,
  MatProgressBarModule,
  MatTabsModule,
  MatDatepickerModule, 
  MatNativeDateModule
} from '@angular/material'


@NgModule({
  imports: [
    CommonModule,
    ScrollingModule,
    MatButtonModule,
    MatCheckboxModule,
    MatCardModule,
    MatToolbarModule,
    MatIconModule,
    MatDialogModule,
    MatTooltipModule,
    MatFormFieldModule,
    MatStepperModule,
    MatInputModule,
    MatSelectModule,
    MatMenuModule,
    MatSidenavModule,
    MatDialogModule,
    MatDividerModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatListModule,
    MatGridListModule,
    MatBadgeModule,
    MatTreeModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatSortModule,
    MatProgressBarModule,
    MatTabsModule,
    MatDatepickerModule, 
    MatNativeDateModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatCardModule,
    MatToolbarModule,
    MatIconModule,
    MatDialogModule,
    MatTooltipModule,
    MatFormFieldModule,
    MatStepperModule,
    MatInputModule,
    MatSelectModule,
    MatMenuModule,
    MatSidenavModule,
    MatDialogModule,
    MatDividerModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatListModule,
    MatGridListModule,
    MatBadgeModule,
    MatTreeModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatSortModule,
    MatProgressBarModule,
    MatTabsModule,
    ScrollingModule,
    MatDatepickerModule, 
    MatNativeDateModule
  ],
  declarations: []
})
export class MaterialModule { }
